version:
  config: "1.0.0"
  service: "0.0.1-SNAPSHOT"

server:
  port: 9001

spring:
  data:
    mongodb:
      database: drl-he-ep-db
      uri: mongodb+srv://dbReadWriteUser:sn7SYqlBNfxXhm7O@dc1.d5hdy.mongodb.net
